from __future__ import annotations
"""Aggregate the frozen 24-seed held-out policy output and compute paired CIs.

Input rows must be generated by run_final_validation_v18.py. This script does
not select parameters; it only aggregates the already locked k_max=3 test.
"""
import argparse
from pathlib import Path
import numpy as np
import pandas as pd


def aggregate(raw: pd.DataFrame) -> pd.DataFrame:
    required = {
        "policy", "seed", "any_failure_rate", "overthreshold_shard_epoch",
        "top1_hit_rate", "mean_brier", "mean_moved_nodes", "mean_controller_ms",
    }
    missing = required - set(raw.columns)
    if missing:
        raise ValueError(f"missing columns: {sorted(missing)}")
    counts = raw.groupby("policy")["seed"].nunique()
    if not counts.eq(24).all():
        raise ValueError(f"expected exactly 24 distinct paired seeds per policy; got {counts.to_dict()}")
    return (
        raw.groupby("policy", as_index=False)
        .agg(
            any_failure_rate_mean=("any_failure_rate", "mean"),
            any_failure_rate_std=("any_failure_rate", "std"),
            overthreshold_shard_epoch_mean=("overthreshold_shard_epoch", "mean"),
            overthreshold_shard_epoch_std=("overthreshold_shard_epoch", "std"),
            top1_hit_rate_mean=("top1_hit_rate", "mean"),
            mean_brier_mean=("mean_brier", "mean"),
            mean_moved_nodes_mean=("mean_moved_nodes", "mean"),
            mean_controller_ms_mean=("mean_controller_ms", "mean"),
            n=("seed", "count"),
        )
        .sort_values("policy")
    )


def paired_bootstrap(raw: pd.DataFrame, draws: int = 10_000) -> pd.DataFrame:
    pivot = raw.pivot(index="seed", columns="policy", values="any_failure_rate").sort_index()
    targets = [
        ("risk_aware_exchange", "no_reconfig"),
        ("risk_aware_exchange", "risk_triggered_random_partner"),
        ("risk_aware_exchange", "random_local_exchange"),
        ("risk_aware_exchange", "periodic_global_reshuffle"),
    ]
    rng = np.random.default_rng(20260630)
    rows = []
    for focal, baseline in targets:
        delta = (pivot[baseline] - pivot[focal]).to_numpy()
        boots = np.array([rng.choice(delta, size=len(delta), replace=True).mean() for _ in range(draws)])
        rows.append(
            {
                "focal": focal,
                "baseline": baseline,
                "n": len(delta),
                "absolute_reduction": float(delta.mean()),
                "ci_low": float(np.quantile(boots, 0.025)),
                "ci_high": float(np.quantile(boots, 0.975)),
                "bootstrap_draws": draws,
                "bootstrap_seed": 20260630,
            }
        )
    return pd.DataFrame(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--raw", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    raw = pd.read_csv(args.raw).sort_values(["policy", "seed"]).reset_index(drop=True)
    aggregate(raw).to_csv(args.out / "heldout_aggregate.csv", index=False)
    paired_bootstrap(raw).to_csv(args.out / "heldout_paired_bootstrap.csv", index=False)

if __name__ == "__main__":
    main()
